const { Resend } = require('resend');

// Initialize Resend client
let resend = null;

function getResend() {
  if (resend) return resend;
  
    const apiKey = process.env.RESEND_API_KEY;
      if (!apiKey) {
          console.warn('[Email] RESEND_API_KEY not configured');
              return null;
                }
                
                  resend = new Resend(apiKey);
                    return resend;
                    }
                    
                    const FROM = () => process.env.SENDER_EMAIL || 'support@repurposeai.ai';
                    const FROM_NAME = 'RepurposeAI';
                    
                    async function sendEmail({ to, subject, html }) {
                      try {
                          const r = getResend();
                              if (!r) return;
                              
                                  await r.emails.send({
                                        from: `${FROM_NAME} <${FROM()}>`,
                                              to,
                                                    subject,
                                                          html
                                                              });
                                                                  console.log(`[Email] Sent "${subject}" to ${to}`);
                                                                    } catch (err) {
                                                                        console.error(`[Email] Failed "${subject}" to ${to}:`, err.message);
                                                                          }
                                                                          }
                                                                          
                                                                          function sendWelcomeEmail(user) {
                                                                            return sendEmail({
                                                                                to: user.email,
                                                                                    subject: 'Welcome to RepurposeAI!',
                                                                                        html: `
                                                                                              <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden">
                                                                                                      <div style="background:linear-gradient(135deg,#7c3aed,#a855f7);padding:32px;text-align:center">
                                                                                                                <h1 style="color:#fff;margin:0;font-size:28px">Welcome to RepurposeAI</h1>
                                                                                                                        </div>
                                                                                                                                <div style="padding:32px">
                                                                                                                                          <p style="font-size:16px;color:#333">Hi ${user.name},</p>
                                                                                                                                                    <p style="font-size:16px;color:#555;line-height:1.6">Thanks for joining RepurposeAI! You're all set to start turning your YouTube videos into engaging content for multiple platforms.</p>
                                                                                                                                                              <div style="text-align:center;margin:32px 0">
                                                                                                                                                                          <a href="https://repurposeai.ai/repurpose" style="background:linear-gradient(135deg,#7c3aed,#a855f7);color:#fff;padding:14px 32px;border-radius:8px;text-decoration:none;font-weight:600;font-size:16px;display:inline-block">Start Repurposing</a>
                                                                                                                                                                                    </div>
                                                                                                                                                                                            </div>
                                                                                                                                                                                                    <div style="background:#f9fafb;padding:20px;text-align:center;border-top:1px solid #eee">
                                                                                                                                                                                                              <p style="font-size:13px;color:#999;margin:0">&copy; ${new Date().getFullYear()} RepurposeAI. All rights reserved.</p>
                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                `
                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                  function sendContactNotification({ name, email, subject, message }) {
                                                                                                                                                                                                                                    return sendEmail({
                                                                                                                                                                                                                                        to: FROM(),
                                                                                                                                                                                                                                            subject: `[Contact Form] ${subject || 'New Message'} from ${name}`,
                                                                                                                                                                                                                                                html: `
                                                                                                                                                                                                                                                      <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden">
                                                                                                                                                                                                                                                              <div style="background:#1e293b;padding:24px;text-align:center">
                                                                                                                                                                                                                                                                        <h2 style="color:#fff;margin:0;font-size:22px">New Contact Form Submission</h2>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                        <div style="padding:28px">
                                                                                                                                                                                                                                                                                                  <table style="width:100%;border-collapse:collapse;font-size:15px">
                                                                                                                                                                                                                                                                                                              <tr><td style="padding:8px 12px;color:#666;font-weight:600">From:</td><td style="padding:8px 12px;color:#333">${name}</td></tr>
                                                                                                                                                                                                                                                                                                                          <tr><td style="padding:8px 12px;color:#666;font-weight:600">Email:</td><td style="padding:8px 12px;color:#333">${email}</td></tr>
                                                                                                                                                                                                                                                                                                                                      <tr><td style="padding:8px 12px;color:#666;font-weight:600">Subject:</td><td style="padding:8px 12px;color:#333">${subject || 'General Inquiry'}</td></tr>
                                                                                                                                                                                                                                                                                                                                                </table>
                                                                                                                                                                                                                                                                                                                                                          <div style="margin-top:20px;padding:16px;background:#f8fafc;border-radius:8px;border-left:4px solid #7c3aed">
                                                                                                                                                                                                                                                                                                                                                                      <p style="font-size:15px;color:#333;line-height:1.6;margin:0;white-space:pre-wrap">${message}</p>
                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                  `
                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                    function sendContactConfirmation({ name, email }) {
                                                                                                                                                                                                                                                                                                                                                                                                      return sendEmail({
                                                                                                                                                                                                                                                                                                                                                                                                          to: email,
                                                                                                                                                                                                                                                                                                                                                                                                              subject: 'We received your message — RepurposeAI',
                                                                                                                                                                                                                                                                                                                                                                                                                  html: `
                                                                                                                                                                                                                                                                                                                                                                                                                        <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                <div style="background:linear-gradient(135deg,#7c3aed,#a855f7);padding:28px;text-align:center">
                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 style="color:#fff;margin:0;font-size:22px">Message Received</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style="padding:28px">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style="font-size:16px;color:#333">Hi ${name},</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style="font-size:16px;color:#555;line-height:1.6">Thanks for reaching out! We've received your message and will get back to you within 24 hours.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style="font-size:14px;color:#999;margin-top:24px">— The RepurposeAI Team</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function sendUpgradeConfirmation(user, plan) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const planName = plan === 'pro' ? 'Pro' : plan === 'enterprise' ? 'Enterprise' : plan;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return sendEmail({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    to: user.email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        subject: `You're now on the ${planName} plan — RepurposeAI`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            html: `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style="background:linear-gradient(135deg,#7c3aed,#a855f7);padding:28px;text-align:center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 style="color:#fff;margin:0;font-size:22px">Upgrade Confirmed!</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style="padding:28px">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p style="font-size:16px;color:#333">Hi ${user.name},</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style="font-size:16px;color:#555;line-height:1.6">Your account has been upgraded to the <strong>${planName}</strong> plan. You now have access to all ${planName} features!</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style="text-align:center;margin:28px 0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <a href="https://repurposeai.ai/repurpose" style="background:linear-gradient(135deg,#7c3aed,#a855f7);color:#fff;padding:14px 32px;border-radius:8px;text-decoration:none;font-weight:600;font-size:16px;display:inline-block">Start Creating</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style="font-size:14px;color:#999;text-align:center">Thank you for supporting RepurposeAI!</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      module.exports = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sendEmail,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          sendWelcomeEmail,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sendContactNotification,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              sendContactConfirmation,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sendUpgradeConfirmation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };const test = 'hello';
